### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by Amund** [denar90/brunch-with-atom#7]
Throw this error on Windows 7, Atom 1.13.1 ia32

```
module.js:457 throw err; ^

Error: Cannot find module 'C:\Users\m.atom\packages\brunch-with-atom\brunch\bin\brunch' at Function.Module._resolveFilename (module.js:455:15) at Function.Module._load (module.js:403:25) at Module.runMain (module.js:590:10) at run (bootstrap_node.js:402:7) at startup (bootstrap_node.js:157:9) at bootstrap_node.js:521:3
```

**Comment by denar90** [comment]
@Amund thanks for reporting that 👍  Haven't even tested on Windows. I'll try to do it.
